{% set name = "paradict" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/paradict-{{ version }}.tar.gz
  sha256: d909d122bf47028a45334eb2280d1e1bcb401fda89986af42c39fd2fadf9de4d

build:
  entry_points:
    - paradict = paradict.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - paradict
  commands:
    - pip check
    - paradict --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/paradict
  summary: Streamable multi-format serialization with schema
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
