{% set name = "paradict" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paradict-{{ version }}.tar.gz
  sha256: 61f1ecf02c251273dbfb1b6b58910d11624b2a03f0c96ad594489b142be643cf

build:
  entry_points:
    - paradict = paradict.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.5
    - braq
    - ustrid
    - written

test:
  imports:
    - paradict
  commands:
    - pip check
    - paradict --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/paradict
  summary: Streamable multi-format serialization with schema
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
